//package ch11exception.lecture;
//
//public class C14throw {
//    public static void main(String[] args) {
//        System.out.println("main code1");
//       try {
//           method3();
//       }catch (Exception e){
//           e.printStackTrace();
//       }
//        System.out.println("main code2");
//    }
////    public static void method3() throws new void Exception throws Exception {
////        throw new Exception(); //throw  new Exceptiop()
////    }
////}
////    public static void method3()throws Exception{--꼭 명시해줘야 함 //메인을 검사하지 않음
////        throw new Exception(); //throw  new Exceptiop();
//
////    }               //런타입을 제외한  ~exception 코드는 검사를 한다.
////}
////메인을 검사하지 않음//런타입을 제외한  ~exception 코드는 검사를 한다.

package ch11exception.lecture;

public class C14throw {
    public static void main(String[] args) {
        System.out.println("main code1");
        try {
            method3();
        }catch (Exception e ){
            e.printStackTrace();
        }
        System.out.println("mian code2");
    }
    private static void method3() throws Exception {
        throw new Exception();
    }
}